
# OpenSfM will use the default parameters from opensfm/config.py
# Set here any parameter that you want to override for this dataset
# For example:
use_exif_size: no
processes: 8                  # Number of threads to use
feature_type: AKAZE
depthmap_min_consistent_views: 5      # Min number of views that should reconstruct a point for it to be valid
feature_process_size: 1024
#bundle_use_gcp: yes
matching_use_filters: yes
feature_use_adaptive_suppression: yes
